// GENERATED by scripts/pixel-art.py — do not hand-edit.
// Regenerate: python scripts/pixel-art.py

export const CAT4_WALK_RIGHT: string[] = [
  " █        █ \n ██      ██ \n ██████████ \n--████████--\n ███●●●●███ \n  ████████  \n  ███  ███  ",
  " ███    ███ \n ██████████ \n--████████--\n ███●●●●███ \n  ████████  \n  ████████  \n  ███  ███  ",
  " █        █ \n ██      ██ \n ██████████ \n--████████--\n ███●●●●███ \n  ████████  \n  ███  ███  ",
  " ███    ███ \n ██████████ \n--████████--\n ███●●●●███ \n  ████████  \n  ████████  \n  ███  ███  ",
];
export const CAT4_HAPPY: string[] = [
  " █        █ \n ██      ██ \n ██████████ \n--█U████U█--\n ███●UU●███ \n  ████████  \n  ███  ███  ",
  " █        █ \n ██      ██ \n ██████████ \n--█U████U█--\n ███●UU●███ \n  ████████  \n  ███  ███  ",
];
export const CAT4_HUNGRY: string[] = [
  " █        █ \n ██      ██ \n ██████████  ?\n--█o████o█--\n ███●●●●███ \n  ████████  \n  ███  ███  ",
  " █        █ \n ██      ██ \n ██████████   ?\n--█o████o█--\n ███●●●●███ \n  ████████  \n  ███  ███  ",
];
export const CAT4_SLEEP: string[] = [
  " █        █  z\n ██      ██ \n ██████████ \n--█-████-█--\n ███●●●●███ \n  ████████  \n  ███  ███  ",
  " █        █   z\n ██      ██ \n ██████████ \n--█-████-█--\n ███●●●●███ \n  ████████  \n  ███  ███  ",
];
export const CAT4_JUMP: string[] = [
  " █        █ \n ██      ██ \n ██████████ \n--█U████U█--\n ███●UU●███ \n  ████████  \n   ██████   ",
  " █        █ \n ██      ██ \n ██████████ \n--████████--\n ███●●●●███ \n  ████████  \n  ███  ███  ",
];
export const CAT4_BLINK: string = " █        █ \n ██      ██ \n ██████████ \n--█-████-█--\n ███●●●●███ \n  ████████  \n  ███  ███  ";
export const CAT4_EAT: string = " █        █ \n ██      ██ \n ██████████ \n--████████--\n ███●██●███ \n  ████████  \n  ███  ███  ";
export const CAT4_COLORS = {
  walkRight: [
    ".k........k.\n.kk......kk.\n.kkkkkkkkkk.\n--kOkkkkOk--\n.kkkNNNNkkk.\n..kkkkkkkk..\n..kkk..kkk..",
    ".kkk....kkk.\n.kkkkkkkkkk.\n--kOkkkkOk--\n.kkkNNNNkkk.\n..kkkkkkkk..\n..kkkkkkkk..\n..kkk..kkk..",
    ".k........k.\n.kk......kk.\n.kkkkkkkkkk.\n--kOkkkkOk--\n.kkkNNNNkkk.\n..kkkkkkkk..\n..kkk..kkk..",
    ".kkk....kkk.\n.kkkkkkkkkk.\n--kOkkkkOk--\n.kkkNNNNkkk.\n..kkkkkkkk..\n..kkkkkkkk..\n..kkk..kkk..",
  ],
  happy: [
    ".k........k.\n.kk......kk.\n.kkkkkkkkkk.\n--kUkkkkUk--\n.kkkNUUNkkk.\n..kkkkkkkk..\n..kkk..kkk..",
    ".k........k.\n.kk......kk.\n.kkkkkkkkkk.\n--kUkkkkUk--\n.kkkNUUNkkk.\n..kkkkkkkk..\n..kLk..kLk..",
  ],
  hungry: [
    ".k........k.\n.kk......kk.\n.kkkkkkkkkk. ?\n--kokkkkok--\n.kkkNNNNkkk.\n..kkkkkkkk..\n..kkk..kkk..",
    ".k........k.\n.kk......kk.\n.kkkkkkkkkk.  ?\n--kokkkkok--\n.kkkNNNNkkk.\n..kkkkkkkk..\n..kkk..kkk..",
  ],
  sleep: [
    ".k........k. z\n.kk......kk.\n.kkkkkkkkkk.\n--k-kkkk-k--\n.kkkNNNNkkk.\n..kkkkkkkk..\n..kkk..kkk..",
    ".k........k.  z\n.kk......kk.\n.kkkkkkkkkk.\n--k-kkkk-k--\n.kkkNNNNkkk.\n..kkkkkkkk..\n..kkk..kkk..",
  ],
  jump: [
    ".k........k.\n.kk......kk.\n.kkkkkkkkkk.\n--kUkkkkUk--\n.kkkNUUNkkk.\n..kkkkkkkk..\n...kkkkkk...",
    ".k........k.\n.kk......kk.\n.kkkkkkkkkk.\n--kOkkkkOk--\n.kkkNNNNkkk.\n..kkkkkkkk..\n..kkk..kkk..",
  ],
  blink: ".k........k.\n.kk......kk.\n.kkkkkkkkkk.\n--k-kkkk-k--\n.kkkNNNNkkk.\n..kkkkkkkk..\n..kkk..kkk..",
  eat: ".k........k.\n.kk......kk.\n.kkkkkkkkkk.\n--kOkkkkOk--\n.kkkNVVNkkk.\n..kkkkkkkk..\n..kkk..kkk..",
};

export const DOG4_WALK_RIGHT: string[] = [
  " ███    ███ \n ████  ████ \n ██████████ \n ██████████ \n ██████████ \n  ████████  \n  ████████  \n  ███  ███  ",
  " ████  ████ \n ██████████ \n ██████████ \n ██████████ \n  ████████  \n  ████████  \n  ████████  \n  ███  ███  ",
  " ███    ███ \n ████  ████ \n ██████████ \n ██████████ \n ██████████ \n  ████████  \n  ████████  \n  ███  ███  ",
  " ████  ████ \n ██████████ \n ██████████ \n ██████████ \n  ████████  \n  ████████  \n  ████████  \n  ███  ███  ",
];
export const DOG4_HAPPY: string[] = [
  " ███    ███ \n ████  ████ \n ██████████ \n █U██████U█ \n ████●●████ \n  ███●●███  \n  ████████  \n  ███  ███  ",
  " ███    ███ \n ████  ████ \n ██████████ \n █U██████U█ \n ████●●████ \n  ███●●███  \n  ████████  \n  ███  ███  ",
];
export const DOG4_HUNGRY: string[] = [
  " ███    ███ \n ████  ████ \n ██████████  ?\n █o██████o█ \n ██████████ \n  ████████  \n  ████████  \n  ███  ███  ",
  " ███    ███ \n ████  ████ \n ██████████   ?\n █o██████o█ \n ██████████ \n  ████████  \n  ████████  \n  ███  ███  ",
];
export const DOG4_SLEEP: string[] = [
  " ███    ███  z\n ████  ████ \n ██████████ \n █-██████-█ \n ██████████ \n  ████████  \n  ████████  \n  ███  ███  ",
  " ███    ███   z\n ████  ████ \n ██████████ \n █-██████-█ \n ██████████ \n  ████████  \n  ████████  \n  ███  ███  ",
];
export const DOG4_JUMP: string[] = [
  " ███    ███ \n ████  ████ \n ██████████ \n █U██████U█ \n ████●●████ \n  ███●●███  \n  ████████  \n   ██████   ",
  " ███    ███ \n ████  ████ \n ██████████ \n ██████████ \n ██████████ \n  ████████  \n  ████████  \n  ███  ███  ",
];
export const DOG4_BLINK: string = " ███    ███ \n ████  ████ \n ██████████ \n █-██████-█ \n ██████████ \n  ████████  \n  ████████  \n  ███  ███  ";
export const DOG4_EAT: string = " ███    ███ \n ████  ████ \n ██████████ \n ██████████ \n ██████████ \n  ████████  \n  ████████  \n  ███  ███  ";
export const DOG4_COLORS = {
  walkRight: [
    ".kkk....kkk.\n.kkkk..kkkk.\n.kkkkkkkkkk.\n.kOkkkkkkOk.\n.kkWWWWWWkk.\n..kkkkkkkk..\n..kkkkkkkk..\n..kkk..kkk..",
    ".kkkk..kkkk.\n.kkkkkkkkkk.\n.kOkkkkkkOk.\n.kkWWWWWWkk.\n..kkkkkkkk..\n..kkkkkkkk..\n..kkkkkkkk..\n..kkk..kkk..",
    ".kkk....kkk.\n.kkkk..kkkk.\n.kkkkkkkkkk.\n.kOkkkkkkOk.\n.kkWWWWWWkk.\n..kkkkkkkk..\n..kkkkkkkk..\n..kkk..kkk..",
    ".kkkk..kkkk.\n.kkkkkkkkkk.\n.kOkkkkkkOk.\n.kkWWWWWWkk.\n..kkkkkkkk..\n..kkkkkkkk..\n..kkkkkkkk..\n..kkk..kkk..",
  ],
  happy: [
    ".kkk....kkk.\n.kkkk..kkkk.\n.kkkkkkkkkk.\n.kUkkkkkkUk.\n.kkWWNNWWkk.\n..kkkNNkkk..\n..kkkkkkkk..\n..kkk..kkk..",
    ".kkk....kkk.\n.kkkk..kkkk.\n.kkkkkkkkkk.\n.kUkkkkkkUk.\n.kkWWNNWWkk.\n..kkkNNkkk..\n..kkkkkkkk..\n..kLk..kLk..",
  ],
  hungry: [
    ".kkk....kkk.\n.kkkk..kkkk.\n.kkkkkkkkkk. ?\n.kokkkkkkok.\n.kkWWWWWWkk.\n..kkkkkkkk..\n..kkkkkkkk..\n..kkk..kkk..",
    ".kkk....kkk.\n.kkkk..kkkk.\n.kkkkkkkkkk.  ?\n.kokkkkkkok.\n.kkWWWWWWkk.\n..kkkkkkkk..\n..kkkkkkkk..\n..kkk..kkk..",
  ],
  sleep: [
    ".kkk....kkk. z\n.kkkk..kkkk.\n.kkkkkkkkkk.\n.k-kkkkkk-k.\n.kkWWWWWWkk.\n..kkkkkkkk..\n..kkkkkkkk..\n..kkk..kkk..",
    ".kkk....kkk.  z\n.kkkk..kkkk.\n.kkkkkkkkkk.\n.k-kkkkkk-k.\n.kkWWWWWWkk.\n..kkkkkkkk..\n..kkkkkkkk..\n..kkk..kkk..",
  ],
  jump: [
    ".kkk....kkk.\n.kkkk..kkkk.\n.kkkkkkkkkk.\n.kUkkkkkkUk.\n.kkWWNNWWkk.\n..kkkNNkkk..\n..kkkkkkkk..\n...kkkkkk...",
    ".kkk....kkk.\n.kkkk..kkkk.\n.kkkkkkkkkk.\n.kOkkkkkkOk.\n.kkWWWWWWkk.\n..kkkkkkkk..\n..kkkkkkkk..\n..kkk..kkk..",
  ],
  blink: ".kkk....kkk.\n.kkkk..kkkk.\n.kkkkkkkkkk.\n.k-kkkkkk-k.\n.kkWWWWWWkk.\n..kkkkkkkk..\n..kkkkkkkk..\n..kkk..kkk..",
  eat: ".kkk....kkk.\n.kkkk..kkkk.\n.kkkkkkkkkk.\n.kOkkkkkkOk.\n.kkWWVVWWkk.\n..kkkVVkkk..\n..kkkkkkkk..\n..kkk..kkk..",
};

export const FROG4_WALK_RIGHT: string[] = [
  "  ██    ██  \n ██████████ \n ██●●●●●●██ \n ██████████ \n  ████████  \n ███    ███ ",
  "  ██    ██  \n ██████████ \n ██●●●●●●██ \n ██████████ \n  ████████  \n ███    ███ ",
  "  ██    ██  \n ██████████ \n ██●●●●●●██ \n ██████████ \n  ████████  \n ███    ███ ",
  "  ██    ██  \n ██████████ \n ██●●●●●●██ \n ██████████ \n  ████████  \n ███    ███ ",
];
export const FROG4_HAPPY: string[] = [
  "  UU    UU  \n ██████████ \n ██●UUUU●██ \n ██████████ \n  ████████  \n ███    ███ ",
  "  UU    UU  \n ██████████ \n ██●UUUU●██ \n ██████████ \n  ████████  \n ███    ███ ",
];
export const FROG4_HUNGRY: string[] = [
  "  oo    oo  \n ██████████  ?\n ██●●●●●●██ \n ██████████ \n  ████████  \n ███    ███ ",
  "  oo    oo  \n ██████████   ?\n ██●●●●●●██ \n ██████████ \n  ████████  \n ███    ███ ",
];
export const FROG4_SLEEP: string[] = [
  "  --    --   z\n ██████████ \n ██●●●●●●██ \n ██████████ \n  ████████  \n ███    ███ ",
  "  --    --    z\n ██████████ \n ██●●●●●●██ \n ██████████ \n  ████████  \n ███    ███ ",
];
export const FROG4_JUMP: string[] = [
  "  UU    UU  \n ██████████ \n ██●UUUU●██ \n ██████████ \n  ████████  \n   ██████   ",
  "  ██    ██  \n ██████████ \n ██●●●●●●██ \n ██████████ \n  ████████  \n ███    ███ ",
];
export const FROG4_BLINK: string = "  --    --  \n ██████████ \n ██●●●●●●██ \n ██████████ \n  ████████  \n ███    ███ ";
export const FROG4_EAT: string = "  ██    ██  \n ██████████ \n ██████████ \n ██████████ \n  ████████  \n ███    ███ ";
export const FROG4_COLORS = {
  walkRight: [
    "..OO....OO..\n.kkkkkkkkkk.\n.kkNNNNNNkk.\n.kkkkkkkkkk.\n..kkkkkkkk..\n.kWk....kWk.",
    "..OO....OO..\n.kkkkkkkkkk.\n.kkNNNNNNkk.\n.kkkkkkkkkk.\n..kkkkkkkk..\n.kWk....kWk.",
    "..OO....OO..\n.kkkkkkkkkk.\n.kkNNNNNNkk.\n.kkkkkkkkkk.\n..kkkkkkkk..\n.kWk....kWk.",
    "..OO....OO..\n.kkkkkkkkkk.\n.kkNNNNNNkk.\n.kkkkkkkkkk.\n..kkkkkkkk..\n.kWk....kWk.",
  ],
  happy: [
    "..UU....UU..\n.kkkkkkkkkk.\n.kkNUUUUNkk.\n.kkkkkkkkkk.\n..kkkkkkkk..\n.kWk....kWk.",
    "..UU....UU..\n.kkkkkkkkkk.\n.kkNUUUUNkk.\n.kkkkkkkkkk.\n..kkkkkkkk..\n.kLk....kWk.",
  ],
  hungry: [
    "..oo....oo..\n.kkkkkkkkkk. ?\n.kkNNNNNNkk.\n.kkkkkkkkkk.\n..kkkkkkkk..\n.kWk....kWk.",
    "..oo....oo..\n.kkkkkkkkkk.  ?\n.kkNNNNNNkk.\n.kkkkkkkkkk.\n..kkkkkkkk..\n.kLk....kWk.",
  ],
  sleep: [
    "..--....--.. z\n.kkkkkkkkkk.\n.kkNNNNNNkk.\n.kkkkkkkkkk.\n..kkkkkkkk..\n.kWk....kWk.",
    "..--....--..  z\n.kkkkkkkkkk.\n.kkNNNNNNkk.\n.kkkkkkkkkk.\n..kkkkkkkk..\n.kWk....kWk.",
  ],
  jump: [
    "..UU....UU..\n.kkkkkkkkkk.\n.kkNUUUUNkk.\n.kkkkkkkkkk.\n..kkkkkkkk..\n...kkkkkk...",
    "..OO....OO..\n.kkkkkkkkkk.\n.kkNNNNNNkk.\n.kkkkkkkkkk.\n..kkkkkkkk..\n.kWk....kWk.",
  ],
  blink: "..--....--..\n.kkkkkkkkkk.\n.kkNNNNNNkk.\n.kkkkkkkkkk.\n..kkkkkkkk..\n.kWk....kWk.",
  eat: "..OO....OO..\n.kkkkkkkkkk.\n.kkOVVVVOkk.\n.kkkkkkkkkk.\n..kkkkkkkk..\n.kWk....kWk.",
};

export const POOP4: string = "    ████    \n  ████████  \n████████████";
